CREATE TABLE USER(
	ID INTEGER PRIMARY KEY IDENTITY,
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	ENABLE BOOLEAN NOT NULL
);

CREATE TABLE ROLE(
	ID INTEGER PRIMARY KEY IDENTITY,
	ROLE varchar(45) NOT NULL,
);

CREATE TABLE USER_ROLES (
	USER_ID INTEGER PRIMARY KEY,
	ROLE_ID INTEGER,
	FOREIGN KEY (USER_ID) REFERENCES USER(ID),
	FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);


CREATE TABLE ENGINEER_INFO(
	ID INTEGER PRIMARY KEY IDENTITY,
	NAME VARCHAR(40) NOT NULL,
	PHONE VARCHAR(12) NOT NULL,
	EMAIL VARCHAR(30),
	BIRTHDAY DATE NOT NULL,
	DESCRIPTION VARCHAR(50) NOT NULL
);

CREATE TABLE USER_DATA(
	ID INTEGER PRIMARY KEY IDENTITY,
	NAME VARCHAR(30) NOT NULL,
	LAST_NAME VARCHAR(30) NOT NULL,
	ADDRESS VARCHAR(50) NOT NULL,
	PHONE VARCHAR(12) NOT NULL,
	EMAIL VARCHAR(30),
	BIRTHDAY DATE NOT NULL,
	USER_ID INTEGER,
	FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE CAR_DATA(
	ID INTEGER PRIMARY KEY IDENTITY,
	BRAND VARCHAR(30) NOT NULL,
	MODEL VARCHAR(30) NOT NULL,
	COLOR VARCHAR(30) NOT NULL,
	USER_ID INTEGER,
	FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE CHECK_IN(
	ID INTEGER PRIMARY KEY IDENTITY,
	CAR_DATA_ID INTEGER,
	FOREIGN KEY (CAR_DATA_ID) REFERENCES CAR_DATA(ID)
	
);

CREATE TABLE SCHEDULE(
	ID INTEGER PRIMARY KEY IDENTITY,
	DATE TIMESTAMP NOT NULL,
	DESCRIPTION VARCHAR(200),
	USER_ID INTEGER,
	FOREIGN KEY (USER_ID) REFERENCES USER(ID),
	ENGINEER_INFO_ID INTEGER,
	FOREIGN KEY (ENGINEER_INFO_ID) REFERENCES ENGINEER_INFO(ID),
	CAR_DATA_ID INTEGER,
	FOREIGN KEY (CAR_DATA_ID) REFERENCES CAR_DATA(ID),
);

INSERT INTO ENGINEER_INFO(NAME,PHONE,EMAIL,BIRTHDAY,DESCRIPTION)
VALUES('bla','bla','bla','2015-10-10','das');


INSERT INTO USER(USERNAME,PASSWORD,ENABLE)
VALUES ('admin','123456', true);
INSERT INTO USER(USERNAME,PASSWORD,ENABLE)
VALUES ('user','123456', true);

INSERT INTO ROLE(ID,ROLE)
VALUES (1,'ROLE_ADMIN');
INSERT INTO ROLE(ID,ROLE)
VALUES (0, 'ROLE_USER');

INSERT INTO CAR_DATA(BRAND,MODEL,COLOR,USER_ID)
VALUES('Ford','Explorer','Blue',0);

INSERT INTO USER_DATA(NAME,LAST_NAME,ADDRESS,PHONE,EMAIL,BIRTHDAY,USER_ID)
VALUES('Jessica','Gerardo','calle Ambar','646-100-0000','yessica.gerardo@softtek.com','1991-12-21',0);


INSERT INTO SCHEDULE(DATE,DESCRIPTION,USER_ID,ENGINEER_INFO_ID,CAR_DATA_ID)
VALUES('2015-10-10 10:00:00', 'Something here',0,0,0);

