CREATE TABLE USER(
	ID INTEGER PRIMARY KEY IDENTITY,
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	ENABLE BOOLEAN NOT NULL
);

CREATE TABLE USER_ROLES (
	USERNAME varchar(45) NOT NULL,
	ROLE varchar(45) NOT NULL,
	USER_ID INTEGER,
	FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE ENGINEER_INFO(
	ID INTEGER PRIMARY KEY IDENTITY,
	NAME VARCHAR(40) NOT NULL,
	PHONE VARCHAR(12) NOT NULL,
	EMAIL VARCHAR(30),
	BIRTHDAY DATE NOT NULL,
	DESCRIPTION VARCHAR(50) NOT NULL
);

CREATE TABLE USER_DATA(
	ID INTEGER PRIMARY KEY IDENTITY,
	NAME VARCHAR(30) NOT NULL,
	LAST_NAME VARCHAR(30) NOT NULL,
	ADDRESS VARCHAR(50) NOT NULL,
	PHONE VARCHAR(12) NOT NULL,
	EMAIL VARCHAR(30),
	BIRTHDAY DATE NOT NULL,
	USER_ID INTEGER,
	FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE CAR_DATA(
	ID INTEGER PRIMARY KEY IDENTITY,
	BRAND VARCHAR(30) NOT NULL,
	MODEL VARCHAR(30) NOT NULL,
	COLOR VARCHAR(30) NOT NULL,
	USER_ID INTEGER,
	FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE CHECK_IN(
	ID INTEGER PRIMARY KEY IDENTITY,
	
	CAR_DATA_ID INTEGER,
	FOREIGN KEY (CAR_DATA_ID) REFERENCES CAR_DATA(ID)
	
);

CREATE TABLE SCHEDULE(
	ID INTEGER PRIMARY KEY IDENTITY,
	DATE DATE NOT NULL,
	DESCRIPTION VARCHAR(200),
	USER_ID INTEGER,
	FOREIGN KEY (USER_ID) REFERENCES USER(ID),
	ENGINEER_INFO_ID INTEGER,
	FOREIGN KEY (ENGINEER_INFO_ID) REFERENCES ENGINEER_INFO(ID),
	CAR_DATA_ID INTEGER,
	FOREIGN KEY (CAR_DATA_ID) REFERENCES CAR_DATA(ID),
);


INSERT INTO USER(USERNAME,PASSWORD,ENABLE)
VALUES ('admin','123456', true);
INSERT INTO USER(USERNAME,PASSWORD,ENABLE)
VALUES ('user','123456', true);

INSERT INTO USER_ROLES (USERNAME, ROLE, USER_ID)
VALUES ('admin', 'ROLE_ADMIN',1);
INSERT INTO USER_ROLES (USERNAME, ROLE, USER_ID)
VALUES ('user', 'ROLE_USER',0);