

CREATE TABLE USER(
	Id INTEGER PRIMARY KEY IDENTITY,
	Username VARCHAR(20) NOT NULL,
	Password VARCHAR(20) NOT NULL
);


CREATE TABLE ENGINEER_INFO(
	Id INTEGER PRIMARY KEY IDENTITY,
	Name VARCHAR(40) NOT NULL,
	Phone VARCHAR(12) NOT NULL,
	Email VARCHAR(30),
	Birthday DATE NOT NULL,
	Description VARCHAR(50) NOT NULL
);

CREATE TABLE USER_DATA(
	Id INTEGER PRIMARY KEY IDENTITY,
	Name VARCHAR(30) NOT NULL,
	Last_Name VARCHAR(30) NOT NULL,
	Address VARCHAR(50) NOT NULL,
	Phone VARCHAR(12) NOT NULL,
	Email VARCHAR(30),
	Birthday DATE NOT NULL,
	User_Id INTEGER,
	FOREIGN KEY (User_Id) REFERENCES USER(Id)
);

CREATE TABLE CAR_DATA(
	Id INTEGER PRIMARY KEY IDENTITY,
	Brand VARCHAR(30) NOT NULL,
	Model VARCHAR(30) NOT NULL,
	Color VARCHAR(30) NOT NULL,
	User_Id INTEGER,
	FOREIGN KEY (User_Id) REFERENCES USER(Id)
);



INSERT INTO USER(Username, Password)
VALUES('admin','admin123');

